[package]
name = "fastcache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8"
crossbeam-queue = "0.3"
crossbeam-utils = "0.8"
dashmap = { version = "5", features = ["inline"] }
